# Javascript Node CircleCI 2.0 configuration file
#
# Check {{ '/2.0/language-javascript/' | docs_url }} for more details
#
version: 2.1

defaults: &defaults
  working_directory: ~/thekla
  docker:
    - image: circleci/node:12

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: install dev deps
          command: npm install
          no_output_timeout: 30m

      - run:
          name: build mono repo
          command: npm run lerna:bootstrap
          no_output_timeout: 30m

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/thekla
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/thekla
      - run:
          name: Run tests
          command: npm run test:cov
          no_output_timeout: 30m
      - run:
          name: Collect coverage statistics
          command: npm run test:cov:report
      - codecov/upload:
          file: ./coverage/__total__/lcov.info
#  deploy:
#    <<: *defaults
#    steps:
#      - attach_workspace:
#          at: ~/thekla
#      - run:
#          name: Authenticate with registry
#          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/thekla/.npmrc
#      - run:
#          name: Publish package
#          command: lerna publish from-package --yes

workflows:
  version: 2
  build-thekla:
    jobs:
#      - build
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
#      - deploy:
#          requires:
#            - test
#          filters:
#            tags:
#              only: /^v.*/
#            branches:
#              ignore: /.*/